baseURL = 'https://chumaltd.github.io/luca-doc'
DefaultContentLanguage = "en"
title = 'LucaSuite'
theme = 'hugo-book'
#enableGitInfo = true

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageCode = "en"
    languageName = 'English'
  [languages.ja]
    contentDir = 'content/ja'
    languageCode = "ja"
    languageName = 'Japanese'
    hasCJKLanguage = true

[markup]
  [markup.highlight]
    codeFences = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  BookTheme = "auto"
  BookRepo = 'https://chumaltd.github.io/luca-doc'
  BookComments = false
